volumes:
    prometheus_data:
      driver_opts:
        type: "nfs"
        o: "addr=10.0.1.90,rw,nfsvers=4,async"
        device: ":/docker/prometheus_data"
    grafana_data:
      driver_opts:
        type: "nfs"
        o: "addr=10.0.1.90,rw,nfsvers=4,async"
        device: ":/docker/grafana_data"
    #alertmanager_data:
      #driver_opts:
        #type: "nfs"
        #o: "addr=10.0.1.90,rw,nfsvers=4,async"
        #device: ":/docker/alertmanager_data"

networks:
  front-tier:
  back-tier:

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    #links:
      #- cadvisor:cadvisor
      #- alertmanager:alertmanager
      #- pushgateway:pushgateway
    depends_on:
      #- cadvisor
      - pushgateway
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always

  pushgateway:
    image: prom/pushgateway
    restart: always
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - back-tier
  
  #alertmanager:
    #image: prom/alertmanager
    #ports:
      #- 9093:9093
    #volumes:
      #- ./alertmanager:/etc/alertmanager
      #- alertmanager_data:/alertmanager
    #networks:
      #- back-tier
    #restart: always
    #command:
      #- '--config.file=/etc/alertmanager/config.yml'
      #- '--storage.path=/alertmanager'
