volumes:
  postgres_data:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.1.90,rw,nfsvers=4,async"
      device: ":/docker/postgres_data"

services:
  postgres:
      #image: postgres
      image: 'postgres:alpine'
      volumes:
        - postgres_data:/var/lib/postgresql/data
      #ports:
         #- 5432:5432
      restart: 'always'
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      #image: quay.io/keycloak/keycloak:latest
      image: jboss/keycloak
      restart: 'always'
      environment:
        #KEYCLOAK_FRONTEND_URL: id.plusrelocationservices.com
        PROXY_ADDRESS_FORWARDING: 'true'
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        #DB_PORT: 5432
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8081:8080
      depends_on:
        - postgres
