server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /promtail/positions.yaml

clients:
  #- url: http://loki:3100/loki/api/v1/push
  - url: http://10.0.1.230:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /mnt/plus-efs-01/log/*log
